
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        

    # Set up Docker Buildx for faster builds
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    # Login to Docker Hub
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    # Build and push with dynamic tag
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/movie-recommender:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/movie-recommender:${{ github.sha }}
          
    # Deploy to Kubernetes (if using k8s)
    - name: Deploy to Kubernetes
      if: github.ref == 'refs/heads/main'
      uses: Azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/deployment.yaml
          k8s/service.yaml
        images: ${{ secrets.DOCKER_HUB_USERNAME }}/movie-recommender:${{ github.sha }}
        kubectl-version: latest